github: [clydedz]
ko_fi: clydedsouza
custom:
  [
    "https://sponsor.clydedsouza.net/",
    "https://donate.stripe.com/dRmfZggGd02Oa7dejP0kE00",
    "https://paypal.me/clydedz",
    "https://buymeacoffee.com/clydedsouza",
    "https://www.revolut.me/clydedz/",
  ]
